apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${CONTROLLER_SA_NAME}
  namespace: ${CONTROLLER_NAMESPACE}
  annotations:
    iam.gke.io/gcp-service-account: ${GCP_SA_EMAIL}
  labels:
    app.kubernetes.io/name: pd-label-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pd-label-controller
  labels:
    app.kubernetes.io/name: pd-label-controller
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims","persistentvolumes"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pd-label-controller-viewer
  labels:
    app.kubernetes.io/name: pd-label-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pd-label-controller
subjects:
  - kind: ServiceAccount
    name: ${CONTROLLER_SA_NAME}
    namespace: ${CONTROLLER_NAMESPACE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pd-label-controller
  namespace: ${CONTROLLER_NAMESPACE}
  labels:
    app.kubernetes.io/name: pd-label-controller  
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: pd-label-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pd-label-controller
    spec:
      serviceAccountName: ${CONTROLLER_SA_NAME}
      containers:
        - name: pd-label-controller
          image: danielvaknin/gke-pd-label-controller:v0.1.27