apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pd-label-controller.fullname" . }}-role
  labels:
    {{- include "pd-label-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims","persistentvolumes"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pd-label-controller.fullname" . }}-rolebinding
  labels:
    {{- include "pd-label-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pd-label-controller.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name:  {{ include "pd-label-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}